name: Generate Snake

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: siddhraj1412
          outputs: |
            assets/snake.svg

      - name: Commit snake
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/snake.svg
          git commit -m "Update contribution snake" || exit 0
          git push
